version: '3'

services:
  python3:
    image: 'brikerman/ubuntu20.04_python3:${PYTHON_VERSION}'
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    tty: true